# Generated by Django 4.2.3 on 2023-08-13 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("author", models.CharField(max_length=1000000)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
