# Generated by Django 4.2.3 on 2023-08-15 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("comment", models.TextField()),
                ("reply_to_comment", models.TextField()),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("comment_author", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={
                "verbose_name": "Blog Detail",
                "verbose_name_plural": "Blog Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("author", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Blog_post",
        ),
        migrations.AddField(
            model_name="blogdetail",
            name="blog_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="zed.blogpost"
            ),
        ),
    ]
